name: Deploy Azure rg
on: [push]
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
    
    - name: TF init
      id: init
      run: terraform init
      
    - name: TF validate
      id: validate
      run: terraform validate -no-color
      
    - name: TF plan
      id: plan
      run: terraform plan -no-color


    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
