name: Deploy Azure rg
on:
  push:
    branches: [ "main" ]
jobs:
  tf:
    runs-on: ubuntu-latest
    env:
        TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup TF
      uses: hashicorp/setup-terraform@v3

    - name: TF init
      id: init
      run: cd terraform && terraform init
      
    - name: TF validate
      id: validate
      run: terraform validate
      
    - name: TF plan
      id: plan
      run: terraform plan

    - name: TF apply
      id: apply
      run: terraform plan -auto-approve
      

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
