on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
env:
    TF_VAR_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    TF_VAR_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    TF_VAR_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    TF_VAR_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    TF_VAR_resource_group_name: rg-devops-main
permissions:
  contents: write
  pull-requests: write
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup TF
      uses: hashicorp/setup-terraform@v3
    
    - name: TF init
      id: init
      run: cd terraform && terraform init
      
    - name: TF validate
      id: validate
      run: cd terraform && terraform validate
      
    - name: TF plan
      id: plan
      run: cd terraform && terraform plan -input=false -no-color > ../plan.txt

    - name: Plan output as a comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number || github.event.inputs.issue_number }}
        body-file: plan.txt
      
