on:
  push:
    branches:
      - main
      - test
jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ test, main ]

    env:
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set resource group name
      run: |
        if [[ "${{ matrix.environment }}" == "test" ]]; then
          echo "TF_VAR_resource_group_name=rg-devops-test" >> $GITHUB_ENV
        else
          echo "TF_VAR_resource_group_name=rg-devops-main" >> $GITHUB_ENV
        fi

    - name: Setup TF
      uses: hashicorp/setup-terraform@v3

    - name: TF init
      id: init
      run: cd terraform && terraform init
      
    - name: TF validate
      id: validate
      run: cd terraform && terraform validate
      
    - name: TF plan
      id: plan
      run: cd terraform && terraform plan

    - name: TF apply
      id: apply
      run: cd terraform && terraform apply -auto-approve