on:
  push:
    branches:
      - main
      - test

jobs:
  terraform-main:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    env:
      TF_VAR_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_resource_group_name: rg-devops-main

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd terraform && terraform init
      - run: cd terraform && terraform validate
      - run: cd terraform && terraform plan -input=false
      - run: cd terraform && terraform apply -auto-approve

  terraform-test:
    if: github.ref_name == 'test'
    runs-on: ubuntu-latest
    env:
      TF_VAR_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_resource_group_name: rg-devops-test

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd terraform && terraform init
      - run: cd terraform && terraform validate
      - run: cd terraform && terraform plan -input=false
      - run: cd terraform && terraform apply -auto-approve
