on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
permissions:
  pull-requests: write
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup TF
      uses: hashicorp/setup-terraform@v3

    - name: TF init
      id: init
      run: cd terraform && terraform init
      
    - name: TF validate
      id: validate
      run: cd terraform && terraform validate
      
    - name: TF plan
      id: plan
      run: cd terraform && terraform plan -input=false > plan.txt

    - name: Plan output as a comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: plan.txt
      
